# fly.toml app configuration file generated for crowdfunding-back-end-424 on 2024-02-16T16:13:16+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crowdfunding-back-end-424'
primary_region = 'syd'
console_command = '/code/manage.py shell'
kill_signal = 'SIGINT'
kill_timeout = '5s'


[experimental]
  auto_rollback = true

[build]

[env]
  PORT = '8000'

[[mounts]]
  source = 'dbvol'
  destination = '/dbvol'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 8000
  processes = ['app']

[[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static/'
