# Generated by Django 4.2.3 on 2024-02-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
