# Generated by Django 4.2.3 on 2024-04-14 13:45

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='placeholder-image.png', upload_to=projects.models.upload_to, verbose_name='Image'),
        ),
    ]
