# Generated by Django 4.2.3 on 2024-01-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_pledge_pledge_date_alter_categories_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('Community Empowerment', 'Community Empowerment'), ('Environmental Stewardship', 'Environmental Stewardship'), ('Sustainable Development', 'Sustainable Development'), ('Innovation for Social Impact', 'Innovation for Social Impact'), ('Crisis Response and Relief', 'Crisis Response and Relief'), ('Equity and Inclusion', 'Equity and Inclusion'), ('Education Access', 'Education Access'), ('Tech for Good', 'Tech for Good'), ('Animal Welfare', 'Animal Welfare'), ('Food Security', 'Food Security'), ('Clean Energy Initiatives', 'Clean Energy Initiatives'), ('Health and Wellness', 'Health and Wellness'), ('Community Resilience', 'Community Resilience')], max_length=200),
        ),
    ]
