# Generated by Django 4.2.3 on 2024-01-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_categories_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='projects.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('Equity and Inclusion', 'Equity and Inclusion'), ('Education Access', 'Education Access'), ('Community Resilience', 'Community Resilience'), ('Animal Welfare', 'Animal Welfare'), ('Tech for Good', 'Tech for Good'), ('Sustainable Development', 'Sustainable Development'), ('Health and Wellness', 'Health and Wellness'), ('Innovation for Social Impact', 'Innovation for Social Impact'), ('Clean Energy Initiatives', 'Clean Energy Initiatives'), ('Food Security', 'Food Security'), ('Crisis Response and Relief', 'Crisis Response and Relief'), ('Community Empowerment', 'Community Empowerment'), ('Environmental Stewardship', 'Environmental Stewardship')], max_length=200),
        ),
    ]
