# Generated by Django 4.2.3 on 2024-01-27 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_categories_project_project_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('Sustainable Development', 'Sustainable Development'), ('Health and Wellness', 'Health and Wellness'), ('Education Access', 'Education Access'), ('Food Security', 'Food Security'), ('Crisis Response and Relief', 'Crisis Response and Relief'), ('Community Resilience', 'Community Resilience'), ('Clean Energy Initiatives', 'Clean Energy Initiatives'), ('Environmental Stewardship', 'Environmental Stewardship'), ('Innovation for Social Impact', 'Innovation for Social Impact'), ('Animal Welfare', 'Animal Welfare'), ('Tech for Good', 'Tech for Good'), ('Community Empowerment', 'Community Empowerment'), ('Equity and Inclusion', 'Equity and Inclusion')], max_length=200),
        ),
    ]
