# Generated by Django 4.2.3 on 2024-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_categories_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('Tech for Good', 'Tech for Good'), ('Environmental Stewardship', 'Environmental Stewardship'), ('Community Empowerment', 'Community Empowerment'), ('Innovation for Social Impact', 'Innovation for Social Impact'), ('Community Resilience', 'Community Resilience'), ('Education Access', 'Education Access'), ('Crisis Response and Relief', 'Crisis Response and Relief'), ('Health and Wellness', 'Health and Wellness'), ('Sustainable Development', 'Sustainable Development'), ('Equity and Inclusion', 'Equity and Inclusion'), ('Food Security', 'Food Security'), ('Clean Energy Initiatives', 'Clean Energy Initiatives'), ('Animal Welfare', 'Animal Welfare')], max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='projects.categories'),
        ),
    ]
