# Generated by Django 4.2.3 on 2024-01-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_categories_title_alter_project_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(choices=[('Crisis Response and Relief', 'Crisis Response and Relief'), ('Education Access', 'Education Access'), ('Food Security', 'Food Security'), ('Tech for Good', 'Tech for Good'), ('Health and Wellness', 'Health and Wellness'), ('Equity and Inclusion', 'Equity and Inclusion'), ('Animal Welfare', 'Animal Welfare'), ('Clean Energy Initiatives', 'Clean Energy Initiatives'), ('Community Resilience', 'Community Resilience'), ('Community Empowerment', 'Community Empowerment'), ('Sustainable Development', 'Sustainable Development'), ('Innovation for Social Impact', 'Innovation for Social Impact'), ('Environmental Stewardship', 'Environmental Stewardship')], max_length=200),
        ),
    ]
