# Generated by Django 4.2.3 on 2024-02-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_category_project_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
