# Generated by Django 4.2.3 on 2024-02-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_date_created'),
        ('projects', '0016_alter_categories_title'),
    ]

    operations = [
    ]
