# Generated by Django 4.2.3 on 2024-02-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_categories_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='categories',
            new_name='category',
        ),
    ]
