# Generated by Django 4.2.3 on 2024-02-07 08:01

from django.db import migrations

def create_categories(apps, schema_editor):
    Categories = apps.get_model('projects', 'Categories')
    categories = [
        {'title': 'Envrionmental Stewardship', 'description': 'Projects that promote the responsible use of natural resources and the protection of the environment.'},
        {'title': 'Education Access', 'description': 'Projects that promote access to education for all.'},
        {'title':'Health and Wellness', 'description': 'Projects that promote physical and mental health.'},
        {'title':'Innovation for Social Impact', 'description': 'Projects that use technology and innovation to address social issues.'},
        {'title':'Sustainable Development', 'description': 'Projects that promote sustainable development.'},
        {'title':'Crisis Response and Relief', 'description': 'Projects that provide relief and support in times of crisis.'},
        {'title':'Tech for Good', 'description': 'Projects that use technology for social good.'},
        {'title':'Animal Welfare', 'description': 'Projects that promote the welfare of animals.'},
        {'title':'Clean Energy Initiatives', 'description': 'Projects that promote the use of clean energy.'},
        {'title':'Food Security', 'description': 'Projects that promote food security.'},
        {'title':'Mental Health Support', 'description': 'Projects that promote mental health support.'},
        {'title':'Community Resilience', 'description': 'Projects that promote community resilience.'},
    ]
    for category in categories:
        Categories.objects.create(title=category['title'], description=category['description'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_rename_categories_project_category'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
