# Generated by Django 4.2.3 on 2024-02-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20240207_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Stewardship', 'Stewardship'), ('Education Access', 'Education Access'), ('Health and Wellness', 'Health and Wellness'), ('Innovation for Social Impact', 'Innovation for Social Impact'), ('Sustainable Development', 'Sustainable Development'), ('Crisis Response and Relief', 'Crisis Response and Relief'), ('Tech for Good', 'Tech for Good'), ('Animal Welfare', 'Animal Welfare'), ('Clean Energy Initiatives', 'Clean Energy Initiatives'), ('Food Security', 'Food Security'), ('Mental Health Support', 'Mental Health Support'), ('Community Resilience', 'Community Resilience')], max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='projects.category'),
        ),
    ]
