# Generated by Django 4.2.3 on 2024-02-08 03:20

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('projects', 'Category')
    categories = [
        {'title':'Environmental Stewardship', 'description': 'Projects that promote the responsible use of natural resources and the protection of the environment.'},
        {'title':'Education Access', 'description': 'Projects that promote access to education for all.'},
        {'title':'Health and Wellness', 'description': 'Projects that promote physical and mental health.'},
        {'title':'Innovation for Social Impact', 'description': 'Projects that use technology and innovation to address social issues.'},
        {'title':'Sustainable Development', 'description': 'Projects that promote sustainable development.'},
        {'title':'Crisis Response and Relief', 'description': 'Projects that provide relief and support in times of crisis.'},
        {'title':'Tech for Good', 'description': 'Projects that use technology for social good.'},
        {'title':'Animal Welfare', 'description': 'Projects that promote the welfare of animals.'},
        {'title':'Clean Energy Initiatives', 'description': 'Projects that promote the use of clean energy.'},
        {'title':'Food Security', 'description': 'Projects that promote food security.'},
        {'title':'Mental Health Support', 'description': 'Projects that promote mental health support.'},
        {'title':'Community Resilience', 'description': 'Projects that promote community resilience.'},
    ]
    for category in categories:
        Category.objects.create(title=category['title'], description=category['description'])

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_category_remove_project_category_delete_categories_and_more'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
